services:
  api:
    image: mendableai/firecrawl:latest
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      REDIS_URL: redis://redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright:3000
    depends_on:
      - redis
      - playwright

  worker:
    image: mendableai/firecrawl:latest
    command: pnpm run worker
    environment:
      REDIS_URL: redis://redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright:3000
    depends_on:
      - redis
      - playwright

  redis:
    image: redis:7-alpine

  playwright:
    image: browserless/chrome:latest
    shm_size: 1gb
